In [53]:
import random, math
import numpy as np
from tslearn.metrics import dtw, dtw_path
from timeit import default_timer as timer

In [54]:
# Setting up the inputs
start = timer()

inputSize = 100
Alist = []
for i in range(inputSize):
#   randomx.append(random.randint(1,1000))
    Alist.append(i)
A = np.array(Alist)
print(A)

Blist = []
for i in range(inputSize, inputSize*2):
    #randomy.append(random.randint(1,1000))
    Blist.append(i)
B = np.array(Blist)

print("DONE GENERATING")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
DONE GENERATING


In [ ]:
#Base DTW 
#dtw_score = dtw(x, y)
# Or, if the path is also an important information:
#optimal_path, dtw_score = dtw_path(x, y)

In [55]:
# Modified Dynamic Time Warping Start

In [62]:
# Setting up the sequences

sequenceSize = 5
numberOfSequencesA = math.floor(len(A)/(sequenceSize-1))

print(len(A), numberOfSequencesA)

Asequences = []
Bsequences = []

print(A)
for i in range(numberOfSequencesA):
    startIndex = i*(sequenceSize-1)
    Asubsequence = []
    if i > 0:
        Asubsequence.append(Asequences[i-1][-1])
    for j in range(sequenceSize-1):
        Asubsequence.append(A[startIndex])
        startIndex += 1
    print(np.array(Asubsequence))
    Asequences.append(np.array(Asubsequence))

print(Asequences)
print(type(Asequences[0]))

100 25
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[0 1 2 3]
[3 4 5 6 7]
[ 7  8  9 10 11]
[11 12 13 14 15]
[15 16 17 18 19]
[19 20 21 22 23]
[23 24 25 26 27]
[27 28 29 30 31]
[31 32 33 34 35]
[35 36 37 38 39]
[39 40 41 42 43]
[43 44 45 46 47]
[47 48 49 50 51]
[51 52 53 54 55]
[55 56 57 58 59]
[59 60 61 62 63]
[63 64 65 66 67]
[67 68 69 70 71]
[71 72 73 74 75]
[75 76 77 78 79]
[79 80 81 82 83]
[83 84 85 86 87]
[87 88 89 90 91]
[91 92 93 94 95]
[95 96 97 98 99]
[array([0, 1, 2, 3]), array([3, 4, 5, 6, 7]), array([ 7,  8,  9, 10, 11]), array([11, 12, 13, 14, 15]), array([15, 16, 17, 18, 19]), array([19, 20, 21, 22, 23]), array([23, 24, 25, 26, 27]), array([27, 28, 29, 30, 31]), array([31, 32, 33, 34, 35]), array([35, 36, 37, 38, 39

In [16]:
print(dtw_score)
print(optimal_path)

end = timer()
print(end-start)

0.0
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99)]
0.0356937000178